### ISSUE TITLE
Two Swahili RGL grammars

### ISSUE THREAD

**Issue by heatherleaf** [GrammaticalFramework/gf-rgl#106]
Since the adoption of PR #32 the RGL now contains two Swahili grammars -- `swahili` and `kiswahili`. 

I think this is a problem, how can it be tackled?

**Comment by heatherleaf** [comment]
See this comment by @johnjcamilleri: https://github.com/GrammaticalFramework/gf-rgl/issues/105#issuecomment-451128379

> For Swahili, I think there should be a single folder swahili which uses the proper ISO code Swa.
Then if one of the two implementations is to be deprecated then put that in swahili/old or similar, and document this in swahili/README.md.
> 
> If the two implementations should really both be considered active (which is doubtful) then they should be in swahili/v1 and swahili/v2, use the same ISO code, and you need to devise some way of choosing which one gets compiled by the RGL build script, e..g using symlinks. But this is less desirable.

**Comment by inariksit** [comment]
PR #341 fixes this in the way John suggested.
