### ISSUE TITLE
Forking out experimental parts

### ISSUE THREAD

**Issue by heatherleaf** [GrammaticalFramework/gf-rgl#119]
In order to simplify the structure of the RGL, I suggest to move the experimental parts (e.g., `experimental`, `parametric`) to a fork of the main repo.

@aarneranta I assume this is mostly your work?

**Comment by inariksit** [comment]
I have moved the directories `experimental` and `parametric` into a branch called `experimental`: https://github.com/GrammaticalFramework/gf-rgl/tree/experimental/src/experimental#readme

Is this an acceptable solution?

**Comment by inariksit** [comment]
I assume the silence means this is acceptable. If not, feel free to reopen the issue.
