### ISSUE TITLE
Add progressiveVPSlash?

### ISSUE THREAD

**Issue by davidar** [GrammaticalFramework/gf-rgl#270]
There doesn't seem to be an equivalent to `progressiveVP` that works on `VPSlash`, which makes it difficult to represent (relative) phrases like "the one which you are holding". Would it be possible to add this to the API?

I hacked together the following which seems to work for English, but I'm not sure I'm familiar enough with the internal API to implement it properly.

```gf
fun ProgrVPSlash : VPSlash -> VPSlash;
lin ProgrVPSlash vp =
  insertObjc (\\a => vp.ad ! a ++ vp.prp ++ vp.p ++ vp.s2 ! a)
    (predAux auxBe ** {c2 = vp.c2; gapInMiddle = vp.gapInMiddle; missingAdv = vp.missingAdv});
```

**Comment by inariksit** [comment]
@davidar Thanks for the initiative! We have kept the RGL API unchanged for several years, but this would be great for the Extend module, see [github.com/GrammaticalFramework/gf-rgl/blob/master/src/abstract/Extend.gf](https://github.com/GrammaticalFramework/gf-rgl/blob/master/src/abstract/Extend.gf). Your implementation for English seems good to me, feel free to add it to the abstract syntax! [Here](https://github.com/GrammaticalFramework/gf-rgl/blob/master/src/abstract/Extend.gf#L95-L106) are some other functions on VPSlash, you can just add it among them and make a pull request!

**Comment by krangelov** [comment]
I have missed that function too. The reason why I didn't add it is that it
adds spurious ambiguities:

PredVP (UsePron i_Pron) (ProgrVP (ComplSlash (SlashV2a read_V2) (DetCN
(DetQuant IndefArt NumSg) (UseN book_N))))

and

PredVP (UsePron i_Pron) (ComplSlash (ProgrVPSlash (SlashV2a read_V2))
(DetCN (DetQuant IndefArt NumSg) (UseN book_N)))

are now two possible trees for "I am reading a book". Does anyone have an
idea for how to avoid this?
