### ISSUE TITLE
German question clause predicate verb error

### ISSUE THREAD

**Issue by yuosef46** [GrammaticalFramework/gf-rgl#382]
While producing the German sentence "Was sind die Neuigkeiten" using the structure below:
```haskell
mkPhr(mkQS
    (presentTense)
    (simultaneousAnt)
    (mkQCl 
      (whatPl_IP)
      (mkNP
          (thePl_Det)
            (mkN ("Neuigkeit")))
      ));
```
I have tried using ```whatSg_IP``` and ```what_IP``` but the machine keep giving this outout "Was ist die Neuigkeiten"

**Comment by aarneranta** [comment]
Hi Yousef,


Thanks for the report! There was indeed a bug, probably a typo, in StructuralGer causing this. It has been fixed now.


Regards


  Aarne


________________________________
From: Yousef Almesbahi ***@***.***>
Sent: Friday, November 19, 2021 11:05:56 AM
To: GrammaticalFramework/gf-rgl
Cc: Subscribed
Subject: [GrammaticalFramework/gf-rgl] German question clause predicate verb error (Issue #382)


While producing the German sentence "Was sind die Neuigkeiten" using the structure below:

mkPhr(mkQS
    (presentTense)
    (simultaneousAnt)
    (mkQCl
      (whatPl_IP)
      (mkNP
          (thePl_Det)
            (mkN ("Neuigkeit")))
      ));

I have tried using whatSg_IP and what_IP but the machine keep giving this outout "Was ist die Neuigkeiten"
