### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by johnjcamilleri** [GrammaticalFramework/gf-rgl#4]
It would be nice to have Travis set up for gf-rgl repository too.
I think rather than compiling GF from scratch it should download the latest stable binary and build the RGL against that, if possible. It's possible that the build script[s] will need to be updated to signal errors via exit values or similar.

**Comment by odanoburu** [comment]
I'm working on it @johnjcamilleri ! will update here.

**Comment by odanoburu** [comment]
we should probably reopen this while we work on these:

@johnjcamilleri said on #5 :

> 1. Have you tested what happens if some GF compilation fails? If it's only looking at the exit value of running Make.sh, it may stay report the build as passing...
 >  2. This is using Make.sh which is supported but not the primary build method. Would adding a Haskell dependency and using Make.hs instead make the build a lot slower? Is there even a way to have multiple separate builds on Travis (one for each build method, including Windows?)

1. [ ] have the build fail when GF can't build the RGL (it currently doesn't #6) 
2. [ ] add haskell build support
3. [ ] add multiple OS CI (is windows possible using docker containers?)
