### ISSUE TITLE
[Question] install path

### ISSUE THREAD

**Issue by bulvara** [GrammaticalFramework/gf-rgl#403]
I've tried to pass my desired install path via _runhaskell Setup copy --dest="$pkgdir"_ but it got ignored.

My gf-core is compiled from source and residing at:
```
/usr/lib/libHSgf-3.11.0-[symbol]-ghc9.0.2.so
/usr/share/grammatical-framework/
/usr/lib/ghc-9.0.2/site-local/gf-3.11.0/Data/
```
Where shall I put {alltenses,prelude,present}/*.gfo ?

**Comment by inariksit** [comment]
The short answer is, anywhere you like, and then record that path into an environment variable called `$GF_LIB_PATH`, so the GF executable knows where to find them.

If you run into problems with this, you can use the diagnostics from this answer https://stackoverflow.com/questions/69909932/how-to-install-the-rgl-for-the-latest-version-of-gf/69928450#69928450 to see where the GF compiler thinks the files are. Or if you have any other questions unanswered in that SO answer, just ask here!

**Comment by bulvara** [comment]
This works, thank you very much.
