### ISSUE TITLE
Copy should preserve timestamps

### ISSUE THREAD

**Issue by johnjcamilleri** [GrammaticalFramework/gf-rgl#43]
Copying gfo files should preserve timestamps to minimise rebuilding of application grammars

**Comment by odanoburu** [comment]
this refers to all build scripts or one in particular, @johnjcamilleri ?

**Comment by johnjcamilleri** [comment]
I think the main priority is the Haskell build script `Make.hs` since this is the one for "power users".
But of course this would be a welcome addition to the other scripts too. Probably easy to implement, just haven't taken the time to look into it.

**Comment by odanoburu** [comment]
should we close this or wait for testing?
