### ISSUE TITLE
ParadigmsGer.anAcc_Prep is missing a type definition

### ISSUE THREAD

**Issue by michmech** [GrammaticalFramework/gf-rgl#438]
The preposition anAcc_Prep is defined on line 532 of Paradigms.gf:

```
anAcc_Prep = mkPrep "an" "an den" "an die" "ans" accusative ;
```

But the *type* of anAcc_Prep is not defined anywhere. This probably doesn’t matter because the GF compiler can probably imply the type. But for readability I suggest adding the type definition somewhere between lines 202 and 208:

```
anAcc_Prep : Prep ; -- an + accusative, with contraction ans
```

This one line probably slipped through @hleiss's fingers during commit c8a424c.

**Comment by hleiss** [comment]
Right. The suggested type declaration has been added in a later commit, so that you don't need to look at the definition of anAcc_Prep = mkPrep ...  or the type declaration of mkPrep any more.
